/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#ifndef	_BasicSafetyMessage_H_
#define	_BasicSafetyMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include "BsmBody.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BasicSafetyMessage */
typedef struct BasicSafetyMessage {
	DSRCmsgID_t	 dsrcMsgId;
	BsmBody_t	 bsmBody;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicSafetyMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicSafetyMessage;

#ifdef __cplusplus
}
#endif

#endif	/* _BasicSafetyMessage_H_ */
#include <asn_internal.h>
