/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#include "BsmBody.h"

static int
memb_partII_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 8)) {
		/* Perform validation of the inner elements */
		return td->check_constraints(td, sptr, ctfailcb, app_key);
	} else {
		_ASN_CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_partII_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_partII_constr_3 GCC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_partII_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_BSMpartIIExtension,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_partII_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_partII_specs_3 = {
	sizeof(struct partII),
	offsetof(struct partII, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_partII_3 = {
	"partII",
	"partII",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_partII_tags_3,
	sizeof(asn_DEF_partII_tags_3)
		/sizeof(asn_DEF_partII_tags_3[0]) - 1, /* 1 */
	asn_DEF_partII_tags_3,	/* Same as above */
	sizeof(asn_DEF_partII_tags_3)
		/sizeof(asn_DEF_partII_tags_3[0]), /* 2 */
	&asn_PER_type_partII_constr_3,
	asn_MBR_partII_3,
	1,	/* Single element */
	&asn_SPC_partII_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_BsmBody_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct BsmBody, coreData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BSMcoreData,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"coreData"
		},
	{ ATF_POINTER, 1, offsetof(struct BsmBody, partII),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_partII_3,
		memb_partII_constraint_1,
		&asn_PER_memb_partII_constr_3,
		0,
		"partII"
		},
};
static int asn_MAP_BsmBody_oms_1[] = { 1 };
static ber_tlv_tag_t asn_DEF_BsmBody_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_BsmBody_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* coreData */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* partII */
};
static asn_SEQUENCE_specifics_t asn_SPC_BsmBody_specs_1 = {
	sizeof(struct BsmBody),
	offsetof(struct BsmBody, _asn_ctx),
	asn_MAP_BsmBody_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_BsmBody_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* Start extensions */
	3	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_BsmBody = {
	"BsmBody",
	"BsmBody",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_BsmBody_tags_1,
	sizeof(asn_DEF_BsmBody_tags_1)
		/sizeof(asn_DEF_BsmBody_tags_1[0]), /* 1 */
	asn_DEF_BsmBody_tags_1,	/* Same as above */
	sizeof(asn_DEF_BsmBody_tags_1)
		/sizeof(asn_DEF_BsmBody_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_BsmBody_1,
	2,	/* Elements count */
	&asn_SPC_BsmBody_specs_1	/* Additional specs */
};

