/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#ifndef	_BsmBody_H_
#define	_BsmBody_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BSMcoreData.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BSMpartIIExtension;

/* BsmBody */
typedef struct BsmBody {
	BSMcoreData_t	 coreData;
	struct partII {
		A_SEQUENCE_OF(struct BSMpartIIExtension) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *partII;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BsmBody_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BsmBody;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BSMpartIIExtension.h"

#endif	/* _BsmBody_H_ */
#include <asn_internal.h>
