/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#include "DSRCmsgIDEnum.h"

int
DSRCmsgIDEnum_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static void
DSRCmsgIDEnum_1_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_NativeEnumerated.free_struct;
	td->print_struct   = asn_DEF_NativeEnumerated.print_struct;
	td->check_constraints = asn_DEF_NativeEnumerated.check_constraints;
	td->ber_decoder    = asn_DEF_NativeEnumerated.ber_decoder;
	td->der_encoder    = asn_DEF_NativeEnumerated.der_encoder;
	td->xer_decoder    = asn_DEF_NativeEnumerated.xer_decoder;
	td->xer_encoder    = asn_DEF_NativeEnumerated.xer_encoder;
	td->uper_decoder   = asn_DEF_NativeEnumerated.uper_decoder;
	td->uper_encoder   = asn_DEF_NativeEnumerated.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_NativeEnumerated.per_constraints;
	td->elements       = asn_DEF_NativeEnumerated.elements;
	td->elements_count = asn_DEF_NativeEnumerated.elements_count;
     /* td->specifics      = asn_DEF_NativeEnumerated.specifics;	// Defined explicitly */
}

void
DSRCmsgIDEnum_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	DSRCmsgIDEnum_1_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

int
DSRCmsgIDEnum_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	DSRCmsgIDEnum_1_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

asn_dec_rval_t
DSRCmsgIDEnum_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	DSRCmsgIDEnum_1_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

asn_enc_rval_t
DSRCmsgIDEnum_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	DSRCmsgIDEnum_1_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

asn_dec_rval_t
DSRCmsgIDEnum_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	DSRCmsgIDEnum_1_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

asn_enc_rval_t
DSRCmsgIDEnum_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	DSRCmsgIDEnum_1_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

asn_dec_rval_t
DSRCmsgIDEnum_decode_uper(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints, void **structure, asn_per_data_t *per_data) {
	DSRCmsgIDEnum_1_inherit_TYPE_descriptor(td);
	return td->uper_decoder(opt_codec_ctx, td, constraints, structure, per_data);
}

asn_enc_rval_t
DSRCmsgIDEnum_encode_uper(asn_TYPE_descriptor_t *td,
		asn_per_constraints_t *constraints,
		void *structure, asn_per_outp_t *per_out) {
	DSRCmsgIDEnum_1_inherit_TYPE_descriptor(td);
	return td->uper_encoder(td, constraints, structure, per_out);
}

static asn_per_constraints_t asn_PER_type_DSRCmsgIDEnum_constr_1 GCC_NOTUSED = {
	{ APC_CONSTRAINED,	 6,  6,  0,  48 }	/* (0..48) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_INTEGER_enum_map_t asn_MAP_DSRCmsgIDEnum_value2enum_1[] = {
	{ 0,	19,	"reservedMessageId-D" },
	{ 1,	17,	"alaCarteMessage-D" },
	{ 2,	20,	"basicSafetyMessage-D" },
	{ 3,	27,	"basicSafetyMessageVerbose-D" },
	{ 4,	21,	"commonSafetyRequest-D" },
	{ 5,	23,	"emergencyVehicleAlert-D" },
	{ 6,	23,	"intersectionCollision-D" },
	{ 7,	9,	"mapData-D" },
	{ 8,	17,	"nmeaCorrections-D" },
	{ 9,	21,	"probeDataManagement-D" },
	{ 10,	18,	"probeVehicleData-D" },
	{ 11,	15,	"roadSideAlert-D" },
	{ 12,	17,	"rtcmCorrections-D" },
	{ 13,	29,	"signalPhaseAndTimingMessage-D" },
	{ 14,	22,	"signalRequestMessage-D" },
	{ 15,	21,	"signalStatusMessage-D" },
	{ 16,	21,	"travelerInformation-D" },
	{ 17,	11,	"uperFrame-D" },
	{ 18,	7,	"mapData" },
	{ 19,	27,	"signalPhaseAndTimingMessage" },
	{ 20,	18,	"basicSafetyMessage" },
	{ 21,	19,	"commonSafetyRequest" },
	{ 22,	21,	"emergencyVehicleAlert" },
	{ 23,	21,	"intersectionCollision" },
	{ 24,	15,	"nmeaCorrections" },
	{ 25,	19,	"probeDataManagement" },
	{ 26,	16,	"probeVehicleData" },
	{ 27,	13,	"roadSideAlert" },
	{ 28,	15,	"rtcmCorrections" },
	{ 29,	20,	"signalRequestMessage" },
	{ 30,	19,	"signalStatusMessage" },
	{ 31,	19,	"travelerInformation" },
	{ 32,	21,	"personalSafetyMessage" },
	{ 240,	13,	"testMessage00" },
	{ 241,	13,	"testMessage01" },
	{ 242,	13,	"testMessage02" },
	{ 243,	13,	"testMessage03" },
	{ 244,	13,	"testMessage04" },
	{ 245,	13,	"testMessage05" },
	{ 246,	13,	"testMessage06" },
	{ 247,	13,	"testMessage07" },
	{ 248,	13,	"testMessage08" },
	{ 249,	13,	"testMessage09" },
	{ 250,	13,	"testMessage10" },
	{ 251,	13,	"testMessage11" },
	{ 252,	13,	"testMessage12" },
	{ 253,	13,	"testMessage13" },
	{ 254,	13,	"testMessage14" },
	{ 255,	13,	"testMessage15" }
};
static unsigned int asn_MAP_DSRCmsgIDEnum_enum2value_1[] = {
	1,	/* alaCarteMessage-D(1) */
	20,	/* basicSafetyMessage(20) */
	2,	/* basicSafetyMessage-D(2) */
	3,	/* basicSafetyMessageVerbose-D(3) */
	21,	/* commonSafetyRequest(21) */
	4,	/* commonSafetyRequest-D(4) */
	22,	/* emergencyVehicleAlert(22) */
	5,	/* emergencyVehicleAlert-D(5) */
	23,	/* intersectionCollision(23) */
	6,	/* intersectionCollision-D(6) */
	18,	/* mapData(18) */
	7,	/* mapData-D(7) */
	24,	/* nmeaCorrections(24) */
	8,	/* nmeaCorrections-D(8) */
	32,	/* personalSafetyMessage(32) */
	25,	/* probeDataManagement(25) */
	9,	/* probeDataManagement-D(9) */
	26,	/* probeVehicleData(26) */
	10,	/* probeVehicleData-D(10) */
	0,	/* reservedMessageId-D(0) */
	27,	/* roadSideAlert(27) */
	11,	/* roadSideAlert-D(11) */
	28,	/* rtcmCorrections(28) */
	12,	/* rtcmCorrections-D(12) */
	19,	/* signalPhaseAndTimingMessage(19) */
	13,	/* signalPhaseAndTimingMessage-D(13) */
	29,	/* signalRequestMessage(29) */
	14,	/* signalRequestMessage-D(14) */
	30,	/* signalStatusMessage(30) */
	15,	/* signalStatusMessage-D(15) */
	33,	/* testMessage00(240) */
	34,	/* testMessage01(241) */
	35,	/* testMessage02(242) */
	36,	/* testMessage03(243) */
	37,	/* testMessage04(244) */
	38,	/* testMessage05(245) */
	39,	/* testMessage06(246) */
	40,	/* testMessage07(247) */
	41,	/* testMessage08(248) */
	42,	/* testMessage09(249) */
	43,	/* testMessage10(250) */
	44,	/* testMessage11(251) */
	45,	/* testMessage12(252) */
	46,	/* testMessage13(253) */
	47,	/* testMessage14(254) */
	48,	/* testMessage15(255) */
	31,	/* travelerInformation(31) */
	16,	/* travelerInformation-D(16) */
	17	/* uperFrame-D(17) */
};
static asn_INTEGER_specifics_t asn_SPC_DSRCmsgIDEnum_specs_1 = {
	asn_MAP_DSRCmsgIDEnum_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_DSRCmsgIDEnum_enum2value_1,	/* N => "tag"; sorted by N */
	49,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static ber_tlv_tag_t asn_DEF_DSRCmsgIDEnum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_DSRCmsgIDEnum = {
	"DSRCmsgIDEnum",
	"DSRCmsgIDEnum",
	DSRCmsgIDEnum_free,
	DSRCmsgIDEnum_print,
	DSRCmsgIDEnum_constraint,
	DSRCmsgIDEnum_decode_ber,
	DSRCmsgIDEnum_encode_der,
	DSRCmsgIDEnum_decode_xer,
	DSRCmsgIDEnum_encode_xer,
	DSRCmsgIDEnum_decode_uper,
	DSRCmsgIDEnum_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_DSRCmsgIDEnum_tags_1,
	sizeof(asn_DEF_DSRCmsgIDEnum_tags_1)
		/sizeof(asn_DEF_DSRCmsgIDEnum_tags_1[0]), /* 1 */
	asn_DEF_DSRCmsgIDEnum_tags_1,	/* Same as above */
	sizeof(asn_DEF_DSRCmsgIDEnum_tags_1)
		/sizeof(asn_DEF_DSRCmsgIDEnum_tags_1[0]), /* 1 */
	&asn_PER_type_DSRCmsgIDEnum_constr_1,
	0, 0,	/* Defined elsewhere */
	&asn_SPC_DSRCmsgIDEnum_specs_1	/* Additional specs */
};

