/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#ifndef	_MessageModuleSet_H_
#define	_MessageModuleSet_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MessageModuleSet */
typedef struct MessageModuleSet {
	DSRCmsgID_t	 dsrcMsgId;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageModuleSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageModuleSet;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageModuleSet_H_ */
#include <asn_internal.h>
