/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "J2735_WXW.ASN"
 */

#ifndef	_RoadSideAlert_H_
#define	_RoadSideAlert_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include "RsaBody.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RoadSideAlert */
typedef struct RoadSideAlert {
	DSRCmsgID_t	 dsrcMsgId;
	RsaBody_t	 rsaBody;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RoadSideAlert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RoadSideAlert;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadSideAlert_H_ */
#include <asn_internal.h>
