/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "DSRCCN_20170918.asn"
 * 	`asn1c -no-gen-example -no-gen-OER`
 */

#ifndef	_SignalState_H_
#define	_SignalState_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IntersectionStatusObject.h"
#include "MinuteOfTheYear.h"
#include "DSecond.h"
#include "PhaseList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignalState */
typedef struct SignalState {
	IntersectionStatusObject_t	 status;
	MinuteOfTheYear_t	*moy	/* OPTIONAL */;
	DSecond_t	*timeStamp	/* OPTIONAL */;
	PhaseList_t	 phases;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalState;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalState_H_ */
#include <asn_internal.h>
